### ISSUE TITLE
prod 下會 asset 載入失敗

### ISSUE THREAD

**Issue by cheetosysst** [cheetosysst/arkhi#21]
@amyD0947639 發現，在 prod 環境下 asset 會全數載入失效，但是 js 部分不會有問題

**Comment by amyD0947639** [comment]
參考[vite-ssr](https://vite-plugin-ssr.com/static-directory#public)和[vite](https://vitejs.dev/guide/assets.html#the-public-directory)裡關於`public`資料夾的相關內容，由於Vite內建從 public/ 目錄中提供靜態資源的方法，因此將靜態資源放至public裡，之後便可以在build時原封不動地複製內容到dist目錄

- 使用資源時要用`/`的方式引用資源
- 不能從JavaScript導入public中的資源
