### ISSUE TITLE
內容管理系統

### ISSUE THREAD

**Issue by cheetosysst** [cheetosysst/arkhi#7]
## 目標

根據範例提供的說明，設計出一套內容管理系統

## 需求

1. 整理出 `/content` 資料夾之下所有的檔案之 metadata (檔名、設定、發文時間、類別)，整理成方便讀取的格式
2. 使用到 TypeScript 的型別，方便往後開發者可以使用編輯器內建的 auto-complete。
3. 熱更新

每個檔案都會需要一個獨立的設定檔，負責存像是

- 標題
- 發文時間
- 上次編輯時間（或許可以讀取文章檔案本身編輯時間？）

**Comment by cheetosysst** [comment]
已經完成基本的 CMS 設計與實做，但有一些小問題仍須調整

**Comment by amyD0947639** [comment]
捨棄舊分支 #10 內容，另建新分支   ##cms-enhance
